### ISSUE TITLE
Incorrect dependencies (?)

### ISSUE THREAD

**Issue by halldc** [conda-forge/r-leaflet.extras-feedstock#2]
I noticed 2 differences between the [recipe](https://github.com/conda-forge/r-leaflet.extras-feedstock/blob/master/recipe/meta.yaml) and the [CRAN page](https://cran.r-project.org/package=leaflet.extras).

* leaflet >=2.0.0
* shiny is not a dependency

@ocefpaf do you know why `shiny` was added as a dependency?

**Comment by ocefpaf** [comment]
I guess that what you are seeing are the old set of dependencies.
The bot does not update the dependencies (yet) so we need to fix that manually.

**Comment by halldc** [comment]
Thanks!

**Comment by ocefpaf** [comment]
Thanks for the report! In the near future the bot may handle that for us.

Please consider adding your :+1: [here](https://github.com/ESIPFed/NUMfocusFallDev/issues/5) to help that happen.

**Comment by halldc** [comment]
Done!
